# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qbfc}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2009-10-11}
  s.description = %q{QBFC-Ruby wraps the QBFC COM object of the QuickBooks 
SDK, providing ease-of-use improvements, such as lower-case method names, 
and find, save, delete, void, and create operations.}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/qbfc.rb",
     "lib/qbfc/base.rb",
     "lib/qbfc/element.rb",
     "lib/qbfc/entities/generated.rb",
     "lib/qbfc/entity.rb",
     "lib/qbfc/info.rb",
     "lib/qbfc/infos/generated.rb",
     "lib/qbfc/item.rb",
     "lib/qbfc/items/generated.rb",
     "lib/qbfc/list.rb",
     "lib/qbfc/lists/account.rb",
     "lib/qbfc/lists/generated.rb",
     "lib/qbfc/lists/qb_class.rb",
     "lib/qbfc/modifiable.rb",
     "lib/qbfc/ole_wrapper.rb",
     "lib/qbfc/qb_collection.rb",
     "lib/qbfc/qb_types.rb",
     "lib/qbfc/qbfc_const.rb",
     "lib/qbfc/report.rb",
     "lib/qbfc/reports/aging.rb",
     "lib/qbfc/reports/budget_summary.rb",
     "lib/qbfc/reports/custom_detail.rb",
     "lib/qbfc/reports/custom_summary.rb",
     "lib/qbfc/reports/general_detail.rb",
     "lib/qbfc/reports/general_summary.rb",
     "lib/qbfc/reports/job.rb",
     "lib/qbfc/reports/payroll_detail.rb",
     "lib/qbfc/reports/payroll_summary.rb",
     "lib/qbfc/reports/rows.rb",
     "lib/qbfc/reports/time.rb",
     "lib/qbfc/request.rb",
     "lib/qbfc/session.rb",
     "lib/qbfc/terms.rb",
     "lib/qbfc/terms/generated.rb",
     "lib/qbfc/transaction.rb",
     "lib/qbfc/transactions/generated.rb",
     "lib/qbfc/voidable.rb",
     "qbfc.gemspec",
     "spec/fixtures/test.lgb",
     "spec/fixtures/test.qbw",
     "spec/fixtures/test.qbw.TLG",
     "spec/integration/add_spec.rb",
     "spec/integration/base_spec.rb",
     "spec/integration/belongs_to_spec.rb",
     "spec/integration/company_spec.rb",
     "spec/integration/conditions_spec.rb",
     "spec/integration/customer_spec.rb",
     "spec/integration/element_finders_spec.rb",
     "spec/integration/quick_test.rb",
     "spec/integration/request_options_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/base_spec.rb",
     "spec/unit/element_finder_spec.rb",
     "spec/unit/element_spec.rb",
     "spec/unit/entities/generated_spec.rb",
     "spec/unit/entity_spec.rb",
     "spec/unit/info/generated_spec.rb",
     "spec/unit/info_spec.rb",
     "spec/unit/item_spec.rb",
     "spec/unit/items/generated_spec.rb",
     "spec/unit/list_finders_spec.rb",
     "spec/unit/list_spec.rb",
     "spec/unit/lists/account_spec.rb",
     "spec/unit/lists/generated_spec.rb",
     "spec/unit/lists/qb_class_spec.rb",
     "spec/unit/modifiable_spec.rb",
     "spec/unit/ole_wrapper_spec.rb",
     "spec/unit/qb_collection_spec.rb",
     "spec/unit/qbfc_const_spec.rb",
     "spec/unit/qbfc_spec.rb",
     "spec/unit/report_spec.rb",
     "spec/unit/request_query_survey.txt",
     "spec/unit/request_spec.rb",
     "spec/unit/session_spec.rb",
     "spec/unit/terms/generated_spec.rb",
     "spec/unit/terms_spec.rb",
     "spec/unit/transaction_finders_spec.rb",
     "spec/unit/transaction_spec.rb",
     "spec/unit/transactions/generated_spec.rb",
     "spec/unit/voidable_spec.rb",
     "tasks/qbfc_tasks.rake"
  ]
  s.homepage = %q{http://rubyforge.org/projects/qbfc/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{qbfc}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A wrapper around the QBFC COM object of the Quickbooks SDK}
  s.test_files = [
    "spec/integration/add_spec.rb",
     "spec/integration/base_spec.rb",
     "spec/integration/belongs_to_spec.rb",
     "spec/integration/company_spec.rb",
     "spec/integration/conditions_spec.rb",
     "spec/integration/customer_spec.rb",
     "spec/integration/element_finders_spec.rb",
     "spec/integration/quick_test.rb",
     "spec/integration/request_options_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/transactions/generated_spec.rb",
     "spec/unit/transaction_finders_spec.rb",
     "spec/unit/transaction_spec.rb",
     "spec/unit/voidable_spec.rb",
     "spec/unit/base_spec.rb",
     "spec/unit/element_finder_spec.rb",
     "spec/unit/element_spec.rb",
     "spec/unit/entities/generated_spec.rb",
     "spec/unit/entity_spec.rb",
     "spec/unit/info/generated_spec.rb",
     "spec/unit/info_spec.rb",
     "spec/unit/items/generated_spec.rb",
     "spec/unit/item_spec.rb",
     "spec/unit/lists/account_spec.rb",
     "spec/unit/lists/generated_spec.rb",
     "spec/unit/lists/qb_class_spec.rb",
     "spec/unit/list_finders_spec.rb",
     "spec/unit/list_spec.rb",
     "spec/unit/modifiable_spec.rb",
     "spec/unit/ole_wrapper_spec.rb",
     "spec/unit/qbfc_const_spec.rb",
     "spec/unit/qbfc_spec.rb",
     "spec/unit/qb_collection_spec.rb",
     "spec/unit/report_spec.rb",
     "spec/unit/request_spec.rb",
     "spec/unit/session_spec.rb",
     "spec/unit/terms/generated_spec.rb",
     "spec/unit/terms_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
